name: CI

on:
  push:
    branches: [ master, main ]
  repository_dispatch:
    types: [Onitool_compile]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      COMPARE: 0 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout agbcc
        uses: actions/checkout@v4
        with:
          path: 'agbcc'
          repository: 'pret/agbcc'

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev build-essential

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Build FireRed
        run: |
          make clean
          make -j2 

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          # Si Sketchware envoie une version, on l'utilise, sinon on utilise le num√©ro de build GitHub
          name: PokeFireRed_${{ github.event.client_payload.version || github.run_number }}
          path: "**/*.gba"
          if-no-files-found: error
          
